source 'https://rubygems.org'
gem 'rack'
gem 'sinatra'
gem 'activesupport'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'tux'
gem 'shotgun'
gem "puma", '~> 3.7'

group :test do
 gem 'capybara'
 gem 'database_cleaner'
 gem 'rspec'
 gem 'pry'
 gem 'shoulda-matchers'
 gem 'rack-test'
 gem 'launchy'
end