development:
 adapter: postgresql
 database: db/the-jazz-music-development

test:
 adapter: postgresql
 database: db/the-jazz-music-test

production:
 adapter: postgresql
 database: db/the-jazz-music-production

